var message = "That's my message!";
var number1 = 2;
var number2 = 3;
console.log(message);
console.log("That's my number 1:" + number1);
console.log("That's my number 2:" + number2);
number1 += number2;
console.log("That's my result:" + number1);
message = message + number1;
console.log("Combined:" + message);
